level1 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
]